# Generated by Django 6.0.2 on 2026-02-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('id_card_front', models.ImageField(upload_to='merchant_ids/', verbose_name='صورة البطاقة (أمام)')),
                ('id_card_back', models.ImageField(upload_to='merchant_ids/', verbose_name='صورة البطاقة (خلف)')),
                ('shop_image', models.ImageField(upload_to='shops/', verbose_name='صورة المحل/الشخصية')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تمت الموافقة من المشرف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(verbose_name='وصف المنتج')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الأساسي')),
                ('image', models.ImageField(upload_to='products/', verbose_name='صورة المنتج الرئيسية')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل (موافقة المشرف)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.merchantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=10, verbose_name='المقاس')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الحالي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='store.merchantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('transaction_type', models.CharField(choices=[('SALE', 'ربح مبيعات'), ('COMPENSATION', 'تعويض (شحن/خصم)'), ('WITHDRAWAL', 'سحب أرباح'), ('REFUND', 'خصم مرتجع')], max_length=20, verbose_name='نوع العملية')),
                ('related_order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الطلب المرتبط')),
                ('description', models.CharField(max_length=255, verbose_name='وصف العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعد العملية')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.wallet')),
            ],
        ),
    ]
