# Generated by Django 6.0.2 on 2026-02-14 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('shipping_address', models.TextField(verbose_name='عنوان الشحن')),
                ('shipping_phone', models.CharField(max_length=15, verbose_name='رقم التواصل')),
                ('total_products_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المنتجات')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم المنصة')),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي النهائي')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'تم التأكيد'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'مرتجع'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('is_first_order', models.BooleanField(default=False, verbose_name='أول طلب (شحن مجاني)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر وقت الشراء')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.merchantprofile', verbose_name='التاجر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productsize', verbose_name='المنتج (المقاس)')),
            ],
        ),
    ]
