# Generated by Django 6.0.2 on 2026-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='عمولة المنصة'),
        ),
    ]
