# Generated by Django 6.0.2 on 2026-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('PENDING', 'قيد الانتظار'), ('APPROVED', 'تم التأكيد'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'مرتجع'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
