# Generated by Django 6.0.2 on 2026-02-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم المحافظة')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='MerchantShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='سعر الشحن')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.governorate')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='store.merchantprofile')),
            ],
            options={
                'unique_together': {('merchant', 'governorate')},
            },
        ),
    ]
