# Generated by Django 6.0.2 on 2026-02-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_governorate_order_governorate_merchantshippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='minimum_balance_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحد الأدنى للرصيد'),
        ),
    ]
