# Generated by Django 6.0.2 on 2026-02-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merchantprofile_minimum_balance_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymobTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymob_order_id', models.CharField(max_length=50, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.merchantprofile')),
            ],
        ),
    ]
