# Generated by Django 6.0.2 on 2026-02-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Elbazaar', max_length=100, verbose_name='اسم الموقع')),
                ('platform_fee_fixed', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='رسوم ثابتة (ج.م)')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=2.75, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='صورة البانر الرئيسي')),
            ],
        ),
    ]
