# Generated by Django 6.0.2 on 2026-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='عمولة المنصة'),
        ),
    ]
