# Generated by Django 6.0.2 on 2026-02-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد معلق'),
        ),
    ]
