# Generated by Django 6.0.2 on 2026-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_wallet_pending_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='is_released',
            field=models.BooleanField(default=False, verbose_name='تم تحرير الرصيد'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'ربح مبيعات'), ('PENDING', 'ربح معلق'), ('COMPENSATION', 'تعويض (شحن/خصم)'), ('WITHDRAWAL', 'سحب أرباح'), ('REFUND', 'خصم مرتجع')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
