# Generated by Django 6.0.2 on 2026-02-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_wallettransaction_is_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed_by_customer',
            field=models.BooleanField(blank=True, null=True, verbose_name='تأكيد العميل'),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_orders', to='store.merchantprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='التقييم (1-5)'),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
    ]
