# Generated by Django 6.0.2 on 2026-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_is_confirmed_by_customer_order_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('WAITING_PAYMENT', 'بانتظار الدفع'), ('PENDING', 'قيد الانتظار'), ('APPROVED', 'تم التأكيد'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'مرتجع'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
