# Generated by Django 6.0.2 on 2026-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='business_description',
            field=models.TextField(default='متجر قديم', verbose_name='وصف النشاط والبضاعة (أنواع، أعداد، أسعار)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='tax_register',
            field=models.FileField(blank=True, null=True, upload_to='merchant_docs/', verbose_name='السجل الضريبي (اختياري)'),
        ),
    ]
