# Generated by Django 6.0.2 on 2026-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_merchantprofile_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='tax_register',
            field=models.FileField(blank=True, null=True, upload_to='merchant_docs/', verbose_name='السجل الضريبي'),
        ),
    ]
