# Generated by Django 6.0.2 on 2026-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_merchantprofile_tax_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='tax_register',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='goods_average_price',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='متوسط الأسعار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='goods_quantity',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='كمية البضاعة المحتملة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='goods_sizes',
            field=models.TextField(default='غير محدد', verbose_name='المقاسات المتاحة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='goods_types',
            field=models.TextField(default='غير محدد', verbose_name='أنواع البضاعة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='tax_register_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل الضريبي'),
        ),
    ]
