# Generated by Django 6.0.2 on 2026-02-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_merchantprofile_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'الدفع عند الاستلام'), ('ONLINE', 'دفع إلكتروني (Paymob)')], default='COD', max_length=10, verbose_name='طريقة الدفع'),
        ),
    ]
