# Generated by Django 6.0.2 on 2026-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='حد الشحن المجاني (عدد قطع)'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='is_free_shipping_active',
            field=models.BooleanField(default=False, verbose_name='تفعيل عرض الشحن المجاني'),
        ),
    ]
