# Generated by Django 6.0.2 on 2026-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_merchantprofile_free_shipping_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='شحن مجاني'),
        ),
        migrations.AddField(
            model_name='offer',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=1, verbose_name='عند شراء X قطع'),
        ),
    ]
