# Generated by Django 6.0.2 on 2026-02-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_offer_free_shipping_offer_free_shipping_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_fee',
        ),
    ]
