# Generated by Django 6.0.2 on 2026-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin_commission',
        ),
        migrations.AddField(
            model_name='product',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='نسبة عمولة المنصة (%)'),
        ),
    ]
