# Generated by Django 6.0.2 on 2026-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_product_admin_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='min_active_balance',
            field=models.DecimalField(decimal_places=2, default=-500.0, max_digits=10, verbose_name='الحد الأدنى لتفعيل المنتجات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='min_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='المبلغ المحجوز في المحفظة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='min_withdrawal_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='الحد الأدنى للسحب'),
        ),
    ]
