# Generated by Django 6.0.2 on 2026-02-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_sitesetting_min_active_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_discount_limit_pct',
            field=models.IntegerField(default=10, verbose_name='أقصى نسبة خصم من الرصيد لكل منتج (%)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='referral_grace_period_hours',
            field=models.IntegerField(default=24, verbose_name='مهلة إدخال كود الدعوة (ساعة)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='قيمة المكافأة (لكل طرف)'),
        ),
    ]
