# Generated by Django 6.0.2 on 2026-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_sitesetting_referral_discount_limit_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='referral_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
