# Generated by Django 6.0.2 on 2026-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_orderitem_referral_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_limit_orders',
            field=models.IntegerField(default=1, verbose_name='عدد الطلبات المؤهلة للمكافأة'),
        ),
    ]
