# Generated by Django 6.0.2 on 2026-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_sitesetting_referral_reward_limit_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'الدفع عند الاستلام'), ('ONLINE', 'دفع إلكتروني (Paymob)'), ('WALLET', 'محفظة إلكترونية')], default='COD', max_length=10, verbose_name='طريقة الدفع'),
        ),
    ]
