# Generated by Django 6.0.2 on 2026-02-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق (علامة زرقاء)'),
        ),
    ]
