# Generated by Django 6.0.2 on 2026-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_merchantprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='product_limit',
            field=models.PositiveIntegerField(default=50, verbose_name='الحد الأقصى للمنتجات'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='نسبة الخصم %'),
        ),
    ]
