# Generated by Django 6.0.2 on 2026-02-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_merchantprofile_product_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='document_type',
            field=models.CharField(choices=[('TERMS', 'شروط وأحكام'), ('PRIVACY', 'سياسة الخصوصية')], default='TERMS', max_length=20, verbose_name='نوع المستند'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'للعملاء'), ('MERCHANT', 'للتجار')], default='CUSTOMER', max_length=20, verbose_name='المستخدم المستهدف'),
        ),
    ]
