# Generated by Django 6.0.2 on 2026-02-26 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_termsandcondition_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان العرض (مثال: هدية لك من الإدارة)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الخصم')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة الخصم %')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='شحن مجاني؟')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
    ]
