# Generated by Django 6.0.2 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_personalvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم معوض من الإدارة'),
        ),
        migrations.AddField(
            model_name='personalvoucher',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='الحد الأقصى للخصم بالطلب (ج.م)'),
        ),
        migrations.AddField(
            model_name='personalvoucher',
            name='remaining_items',
            field=models.PositiveIntegerField(default=1, verbose_name='رصيد المنتجات المسموح للخصم'),
        ),
        migrations.AlterField(
            model_name='personalvoucher',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='نفد الرصيد؟'),
        ),
        migrations.AlterField(
            model_name='personalvoucher',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان العرض'),
        ),
    ]
