# Generated by Django 6.0.2 on 2026-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_order_admin_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوى صفحة من نحن')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
