# Generated by Django 6.0.2 on 2026-02-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='verification_rank',
            field=models.CharField(choices=[('NONE', 'غير موثق'), ('SILVER', 'توثيق فضي'), ('BLUE', 'توثيق أزرق'), ('GOLD', 'توثيق ذهبي')], default='NONE', max_length=10, verbose_name='رتبة التوثيق'),
        ),
    ]
