# Generated by Django 6.0.2 on 2026-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_merchantprofile_verification_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء عرض المنتجات'),
        ),
    ]
