# Generated by Django 6.0.2 on 2026-02-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(verbose_name='نص الشكوى')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة (للتسوية)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='store.order', verbose_name='الطلب')),
            ],
        ),
    ]
