# Generated by Django 6.0.2 on 2026-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_deliverycomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymob_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم معاملة Paymob'),
        ),
    ]
