# Generated by Django 6.0.2 on 2026-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_order_paymob_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم طلب Paymob المبدئي'),
        ),
    ]
