# Generated by Django 6.0.2 on 2026-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_order_paymob_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.AddField(
            model_name='banner',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت انتهاء العرض (اختياري)'),
        ),
    ]
