# Generated by Django 6.0.2 on 2026-02-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_remove_banner_is_active_banner_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'Cart'), ('WAITING_PAYMENT', 'بانتظار الدفع'), ('PENDING', 'قيد الانتظار'), ('PREPARING', 'جاري التحضير'), ('APPROVED', 'تم التأكيد'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('RETURNED', 'مرتجع'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
