# Generated by Django 6.0.2 on 2026-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycomplaint',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الواتساب للتواصل'),
        ),
    ]
