# Generated by Django 6.0.2 on 2026-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_deliverycomplaint_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_received_return',
            field=models.BooleanField(default=False, verbose_name='تأكيد التاجر لاستلام المرتجع'),
        ),
    ]
