# Generated by Django 6.0.2 on 2026-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_order_merchant_received_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستلم'),
        ),
    ]
