# Generated by Django 6.0.2 on 2026-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_order_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='pending_balance_release_hours',
            field=models.PositiveIntegerField(default=24, help_text='عدد الساعات قبل تحرير رصيد التاجر أوتوماتيكياً', verbose_name='مدة تعليق الرصيد (بالساعات)'),
        ),
    ]
