# Generated by Django 6.0.2 on 2026-03-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_sitesetting_pending_balance_release_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='document_type',
            field=models.CharField(choices=[('TERMS', 'شروط وأحكام'), ('PRIVACY', 'سياسة الخصوصية'), ('SHIPPING_RETURN', 'سياسة الشحن والمرتجعات')], default='TERMS', max_length=20, verbose_name='نوع المستند'),
        ),
    ]
