# Generated by Django 6.0.2 on 2026-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_termsandcondition_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('image', models.ImageField(upload_to='promo_popups/', verbose_name='صورة العرض')),
                ('custom_link', models.URLField(blank=True, help_text='مثال: رابط قسم أو منتج معين', null=True, verbose_name='رابط التوجيه')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='مدة العرض (بالأيام)')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='مدة العرض (بالساعات)')),
                ('is_active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التفعيل')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إعلان منبثق (Popup)',
                'verbose_name_plural': 'الإعلانات المنبثقة',
            },
        ),
    ]
