# Generated by Django 6.0.2 on 2026-03-12 21:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_promopopup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promopopup',
            options={'verbose_name': 'إعلان منبثق (Popup)'},
        ),
        migrations.RemoveField(
            model_name='promopopup',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='promopopup',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='promopopup',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.offer', verbose_name='اربط بعرض نشط'),
        ),
        migrations.AlterField(
            model_name='promopopup',
            name='custom_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط مخصص خارجي'),
        ),
        migrations.AlterField(
            model_name='promopopup',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الانتهاء والامخفاء'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promopopup',
            name='image',
            field=models.ImageField(upload_to='promo_popups/', verbose_name='صورة الإعلان'),
        ),
        migrations.AlterField(
            model_name='promopopup',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت بداية الظهور'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promopopup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الإعلان'),
        ),
    ]
