# Generated by Django 6.0.2 on 2026-03-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_userfcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFCMToken',
        ),
    ]
