# Generated by Django 6.0.2 on 2026-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_delete_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تمت المراجعة والقبول'),
        ),
    ]
