# Generated by Django 6.0.2 on 2026-03-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_country_alter_notificationlog_options_and_more'),
        ('store', '0063_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='banner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='promopopup',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='accounts.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم المحافظة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='platform_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='رسوم ثابتة (بالعملة المحلية)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Elbazaar', max_length=100, verbose_name='اسم الموقع/الفرع'),
        ),
        migrations.AlterUniqueTogether(
            name='governorate',
            unique_together={('country', 'name')},
        ),
    ]
