# Generated by Django 6.0.2 on 2026-04-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_country_alter_notificationlog_options_and_more'),
        ('store', '0064_aboutus_country_banner_country_governorate_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='accounts.country', verbose_name='الدولة'),
        ),
    ]
