# Generated by Django 6.0.2 on 2026-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_alter_sitesetting_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='صورة البانر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='pending_balance_release_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='مدة تعليق الرصيد (ساعة)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='platform_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10, verbose_name='رسوم ثابتة'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='referral_discount_limit_pct',
            field=models.IntegerField(default=10, verbose_name='أقصى نسبة خصم للمنتج (%)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='قيمة المكافأة'),
        ),
    ]
