# Generated by Django 6.0.2 on 2026-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_country_alter_notificationlog_options_and_more'),
        ('store', '0066_alter_sitesetting_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='governorate',
            unique_together={('country', 'name')},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_ar',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى صفحة من نحن'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى صفحة من نحن'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم القسم'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم القسم'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم المحافظة'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم المحافظة'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='نص البند'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='content_en',
            field=models.TextField(null=True, verbose_name='نص البند'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان البند'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان البند'),
        ),
        migrations.AlterUniqueTogether(
            name='governorate',
            unique_together={('country', 'name'), ('country', 'name_ar'), ('country', 'name_en')},
        ),
    ]
