# Generated by Django 6.0.2 on 2026-04-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_governorate_unique_together_aboutus_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='id_card_front',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='national_id',
        ),
    ]
