# Generated by Django 6.0.2 on 2026-04-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_remove_merchantprofile_id_card_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymob_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymob_transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة في البوابة'),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المعاملة (Transaction)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_used',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='البوابة المستخدمة (Paymob/Fawaterk)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_payment_gateway',
            field=models.CharField(choices=[('PAYMOB', 'باي موب (Paymob)'), ('FAWATERK', 'فواتيرك (Fawaterk)')], default='FAWATERK', max_length=20, verbose_name='بوابة الدفع الفعالة'),
        ),
        migrations.CreateModel(
            name='WalletDepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_order_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الفاتورة الخارجي')),
                ('gateway_name', models.CharField(default='PAYMOB', max_length=20)),
                ('amount_cents', models.IntegerField(verbose_name='المبلغ بالقروش (لو باي موب)')),
                ('amount_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الفعلي')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.merchantprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymobTransaction',
        ),
    ]
