# Generated by Django 6.0.2 on 2026-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='are_products_hidden',
            field=models.BooleanField(default=False, verbose_name='إيقاف عرض المنتجات إدارياً'),
        ),
    ]
