# Generated by Django 6.0.2 on 2026-04-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_merchantprofile_are_products_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم المنتج'),
        ),
    ]
