# Generated by Django 6.0.2 on 2026-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='goods_sizes',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='expected_sales_quantity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الكميات المتوقع بيعها'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب'),
        ),
    ]
