# Generated by Django 6.0.2 on 2026-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_remove_merchantprofile_goods_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='fawaterk_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='رسوم Fawaterk الثابتة'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='fawaterk_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='نسبة رسوم Fawaterk (%)'),
        ),
    ]
