# Generated by Django 6.0.2 on 2026-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_sitesetting_fawaterk_fee_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='referral_reward_amount',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='نسبة المكافأة من الطلب (%)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='صلاحية رصيد المكافأة (أيام)'),
        ),
    ]
