# Generated by Django 6.0.2 on 2026-04-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_remove_sitesetting_referral_reward_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_type', models.CharField(choices=[('PERCENTAGE', 'نسبة مئوية (%)'), ('FIXED', 'مبلغ ثابت')], default='PERCENTAGE', max_length=20, verbose_name='نوع الكاش باك')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='القيمة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_rule', to='store.merchantprofile', verbose_name='التاجر')),
            ],
        ),
    ]
