# Generated by Django 6.0.2 on 2026-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_merchantcashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_discount_max_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='الحد الأقصى المالي للخصم (بالعملة المحلية)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='referral_reward_max_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='الحد الأقصى المالي للمكافأة (بالعملة المحلية)'),
        ),
    ]
