# Generated by Django 6.0.2 on 2026-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_sitesetting_referral_discount_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='مؤرشف (مخفي من التاجر)'),
        ),
    ]
