# Generated by Django 6.0.2 on 2026-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_product_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_details',
            field=models.CharField(default='غير محدد', max_length=255, verbose_name='تفاصيل الحساب (رقم/IBAN/عنوان)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.CharField(choices=[('INSTAPAY', 'إنستا باي (InstaPay)'), ('WALLET', 'محفظة إلكترونية (Wallet)'), ('BANK', 'حساب بنكي (Bank Account)')], default='WALLET', max_length=20, verbose_name='طريقة السحب'),
        ),
    ]
