# Generated by Django 6.0.2 on 2026-02-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.TextField(default='', help_text='أسماء الصلاحيات مفصول بفاصلة (مثلاً: orders, products)')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customrole', verbose_name='الدور الإداري'),
        ),
    ]
