# Generated by Django 6.0.2 on 2026-02-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_invited_by_user_join_date_user_referral_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_primary',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رصيد الدعوات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'عميل'), ('MERCHANT', 'تاجر'), ('OWNER', 'Owner (مالك)'), ('ADMIN_LVL2', 'مشرف درجة ثانية'), ('ADMIN_LVL3', 'مشرف درجة ثالثة')], default='CUSTOMER', max_length=20),
        ),
    ]
