# Generated by Django 6.0.2 on 2026-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
