# Generated by Django 6.0.2 on 2026-03-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_phone_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('status', models.CharField(max_length=50, verbose_name='الحالة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل/إيرور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجل الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
