# Generated by Django 6.0.2 on 2026-03-17 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدولة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود الدولة (مثل EG)')),
                ('phone_code', models.CharField(max_length=10, verbose_name='كود الاتصال (مثل +20)')),
                ('currency_name', models.CharField(max_length=50, verbose_name='اسم العملة (مثل جنيه)')),
                ('currency_symbol', models.CharField(max_length=10, verbose_name='رمز العملة (مثل ج.م)')),
                ('is_active', models.BooleanField(default=True, verbose_name='دولة مفعلة')),
                ('paymob_integration_id_card', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID دفع البطاقات')),
                ('paymob_integration_id_wallet', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID دفع المحافظ')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={},
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'عميل'), ('MERCHANT', 'تاجر'), ('OWNER', 'مالك النظام (سوبر يوزر)'), ('COUNTRY_ADMIN', 'مدير دولة'), ('ADMIN_LVL2', 'مشرف درجة ثانية'), ('ADMIN_LVL3', 'مشرف درجة ثالثة')], default='CUSTOMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userfcmtoken',
            name='token',
            field=models.CharField(max_length=255, verbose_name='FCM Token'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='accounts.country', verbose_name='الدولة التابع لها'),
        ),
    ]
