# Generated by Django 6.0.2 on 2026-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_country_alter_notificationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='gateway_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10, verbose_name='رسوم بوابة الدفع الثابتة'),
        ),
        migrations.AddField(
            model_name='country',
            name='gateway_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.75, max_digits=5, verbose_name='نسبة رسوم بوابة الدفع (%)'),
        ),
    ]
