# Generated by Django 6.0.2 on 2026-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_country_gateway_fee_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='gateway_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='country',
            name='gateway_fee_percentage',
        ),
        migrations.AddField(
            model_name='country',
            name='fawaterk_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='رسوم Fawaterk الثابتة'),
        ),
        migrations.AddField(
            model_name='country',
            name='fawaterk_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='نسبة رسوم Fawaterk (%)'),
        ),
    ]
