# Generated by Django 6.0.2 on 2026-04-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_country_gateway_fee_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='fawaterk_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fawaterk_fee_percentage',
        ),
    ]
