# Generated by Django 6.0.2 on 2026-04-25 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_country_fawaterk_fee_fixed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المكافأة')),
                ('order_id', models.CharField(max_length=20, verbose_name='من طلب رقم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_expired', models.BooleanField(default=False, verbose_name='انتهت صلاحيته؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
